requires 'Dancer';
requires 'Dancer::Plugin::FlashNote', '1.0.4';
requires 'DateTime';
requires 'DateTime::Format::Human::Duration';
requires 'DateTime::Format::ISO8601';
requires 'File::ShareDir';
requires 'Plack';
requires 'Starman';
requires 'Template';
requires 'Time::HiRes';
requires 'Try::Tiny';
requires 'WebService::Zaqar', '0.008';
